from __future__ import annotations

from dataclasses import dataclass


SCHEMA_VERSION = "0.1"
STAGE = "Stage 4.1"

JOB_COMPLETED_ODB_ACCEPTABLE = "JOB_COMPLETED_ODB_ACCEPTABLE"
JOB_FAILED_WITH_PARTIAL_ODB = "JOB_FAILED_WITH_PARTIAL_ODB"
JOB_FAILED_NO_ODB = "JOB_FAILED_NO_ODB"
JOB_INPUT_PROCESSOR_FAILED = "JOB_INPUT_PROCESSOR_FAILED"
JOB_SOLVER_CONVERGENCE_FAILED = "JOB_SOLVER_CONVERGENCE_FAILED"
JOB_NUMERICAL_INSTABILITY_FAILED = "JOB_NUMERICAL_INSTABILITY_FAILED"
JOB_MESH_DISTORTION_FAILED = "JOB_MESH_DISTORTION_FAILED"
JOB_CONTACT_CONSTRAINT_FAILED = "JOB_CONTACT_CONSTRAINT_FAILED"
JOB_MATERIAL_MODEL_FAILED = "JOB_MATERIAL_MODEL_FAILED"
JOB_THERMAL_COUPLING_FAILED = "JOB_THERMAL_COUPLING_FAILED"
JOB_OUTPUT_MISSING = "JOB_OUTPUT_MISSING"
JOB_ODB_LOCKED = "JOB_ODB_LOCKED"
JOB_RUNNING_LOCK_ACTIVE = "JOB_RUNNING_LOCK_ACTIVE"
JOB_LOCKED_STALE = "JOB_LOCKED_STALE"
JOB_COMPLETED_ODB_MISSING = "JOB_COMPLETED_ODB_MISSING"
JOB_ODB_EXISTS_BUT_COMPLETION_NOT_PROVEN = "JOB_ODB_EXISTS_BUT_COMPLETION_NOT_PROVEN"
JOB_LICENSE_OR_ENVIRONMENT_FAILED = "JOB_LICENSE_OR_ENVIRONMENT_FAILED"
JOB_TERMINATED_BY_ERRORS = "JOB_TERMINATED_BY_ERRORS"
JOB_STATUS_UNKNOWN = "JOB_STATUS_UNKNOWN"

COMPLETED = "completed"
INPUT_PROCESSOR_FAILURE = "input_processor_failure"
SOLVER_CONVERGENCE_FAILURE = "solver_convergence_failure"
NUMERICAL_INSTABILITY = "numerical_instability"
MESH_DISTORTION = "mesh_distortion"
CONTACT_CONSTRAINT_FAILURE = "contact_constraint_failure"
MATERIAL_MODEL_FAILURE = "material_model_failure"
THERMAL_COUPLING_FAILURE = "thermal_coupling_failure"
OUTPUT_OR_ODB_FAILURE = "output_or_odb_failure"
LICENSE_OR_ENVIRONMENT_FAILURE = "license_or_environment_failure"
RUNNING_OR_LOCKED = "running_or_locked"
UNKNOWN = "unknown"


STATUS_TO_CATEGORY = {
    JOB_COMPLETED_ODB_ACCEPTABLE: COMPLETED,
    JOB_FAILED_WITH_PARTIAL_ODB: OUTPUT_OR_ODB_FAILURE,
    JOB_FAILED_NO_ODB: OUTPUT_OR_ODB_FAILURE,
    JOB_INPUT_PROCESSOR_FAILED: INPUT_PROCESSOR_FAILURE,
    JOB_SOLVER_CONVERGENCE_FAILED: SOLVER_CONVERGENCE_FAILURE,
    JOB_NUMERICAL_INSTABILITY_FAILED: NUMERICAL_INSTABILITY,
    JOB_MESH_DISTORTION_FAILED: MESH_DISTORTION,
    JOB_CONTACT_CONSTRAINT_FAILED: CONTACT_CONSTRAINT_FAILURE,
    JOB_MATERIAL_MODEL_FAILED: MATERIAL_MODEL_FAILURE,
    JOB_THERMAL_COUPLING_FAILED: THERMAL_COUPLING_FAILURE,
    JOB_OUTPUT_MISSING: OUTPUT_OR_ODB_FAILURE,
    JOB_ODB_LOCKED: RUNNING_OR_LOCKED,
    JOB_RUNNING_LOCK_ACTIVE: RUNNING_OR_LOCKED,
    JOB_LOCKED_STALE: RUNNING_OR_LOCKED,
    JOB_COMPLETED_ODB_MISSING: OUTPUT_OR_ODB_FAILURE,
    JOB_ODB_EXISTS_BUT_COMPLETION_NOT_PROVEN: OUTPUT_OR_ODB_FAILURE,
    JOB_LICENSE_OR_ENVIRONMENT_FAILED: LICENSE_OR_ENVIRONMENT_FAILURE,
    JOB_TERMINATED_BY_ERRORS: UNKNOWN,
    JOB_STATUS_UNKNOWN: UNKNOWN,
}


@dataclass(frozen=True)
class JobFiles:
    dat: str | None = None
    msg: str | None = None
    sta: str | None = None
    log: str | None = None
    com: str | None = None
    prt: str | None = None
    odb: str | None = None
    lck: str | None = None


def category_for_status(status: str) -> str:
    return STATUS_TO_CATEGORY.get(status, UNKNOWN)

